### ISSUE TITLE
Route [admin.homepages.landing] not defined

### ISSUE THREAD

**Issue by MarcelWeidum** [area17/twill-capsule-homepages#2]
Reproduce:

```mkdir -p app/Twill/Capsules```

```php artisan twill:capsule:install homepages --copy```

Add to `twill-navigation.php`:
```php
'homepages' => [
     'title' => 'Homepage',
     'route' => 'admin.homepages.landing',
 ],
```

Navigate to admin panel and you see the error.

**Comment by MarcelWeidum** [comment]
Looks like it isn't loading the `routes/admin.php` from the capsule.

**Comment by cambad** [comment]
Hello @MarcelWeidum! 

Thanks for the report, it looks like this is the same problem mentioned [here](https://github.com/area17/twill-capsule-homepages/issues/1#issuecomment-846537021). 

There was indeed a problem with the creation of the page (the `admin.homepages.landing` route was supposed to create a new entry in the database), we just pushed a modification that takes over this part. 

I let you try again to install the capsule on a new project with Twill installed and tell me if you encounter the problem. 

If not, I'll let you close the ticket 🙏🏽 

Cheers ✌🏽

**Comment by MDylan** [comment]
Hi,

I have the same error with Twill 3.0.0-rc4
I followed the readme instructions, it's a totally new project.
Do you have any idea for solution?
Thank you!

**Comment by cambad** [comment]
Hello @MDylan, 

For the moment this capsule doesn't support twill 3, I'm going to set up a 2.x branch as soon as I have some time 🏃🏽.

I'll keep you posted here as soon as it's available 🕐  

Thanks for the report 🙏🏽
