### ISSUE TITLE
View [admin._components.seo] not found

### ISSUE THREAD

**Issue by FlickTheManual** [area17/twill-capsule-homepages#3]
Hi there, I've got a strange error, 

I've follow the step here: https://github.com/area17/twill-capsule-homepages/issues/1#issuecomment-846478200;
so, it works, but I've got this error when I go to the Homepage dashboard:

`View [admin._components.seo] not found. (View: app/Twill/Capsules/Homepages/resources/views/admin/form.blade.php).`

on line 29: `@include('admin._components.seo')`, that view does not exist.

Have any idea? thanks for all :smiley:

**Comment by FlickTheManual** [comment]
update on it: I've created a folder named `_components` and then add the `seo.blade.php` file. 
But I really don't know if it's the good practise.

**Comment by cambad** [comment]
Hi @FlickTheManual!

This is only a good practice if you have multiple capsules, so you can refactor and put the repeated code in one file. 

As this repository is only one capsule, I made a change in the code (#4) to integrate the SEO part directly in the form. I don't think this problem will happen anymore. 

Thanks for reporting it! I'll let you try installing the capsule again on a new project with Twill and let me know if you run into any issues 🙏🏽. 

If you no longer have the problem I'll let you close the ticket

Cheers ✌🏽

**Comment by FlickTheManual** [comment]
@cambad ok thanks, I got it, I'll close the ticket

and happy new year 🥳🥳🥳
